config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :brands
  resources :stores

  root 'home#index'

  get 'show' => 'home#show'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  belongs_to :store
  monetize :price
  validates_presence_of :name
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  do_not_validate_attachment_file_type :image
end

app/models/store.rb
class Store < ActiveRecord::Base

	def titleized_name
		self.name.titleize
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :slug)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		#code that determines what data is passed to the view
		#rails magic
	end

	def show
		@some_number = rand(10)
		@boolean = true
		render 'show'
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :brand_id, :store_id, :image, :price)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/brands/_form.html.haml
= form_for @brand do |f|
  - if @brand.errors.any?
    #error_explanation
      %h2= "#{pluralize(@brand.errors.count, "error")} prohibited this brand from being saved:"
      %ul
        - @brand.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :slug
    = f.text_field :slug
  .actions
    = f.submit 'Save'

app/views/brands/edit.html.haml
%h1 Editing brand

= render 'form'

= link_to 'Show', @brand
\|
= link_to 'Back', brands_path

app/views/brands/index.html.haml
%h1 Listing brands

%table
  %thead
    %tr
      %th Name
      %th Slug
      %th
      %th
      %th

  %tbody
    - @brands.each do |brand|
      %tr
        %td= brand.name
        %td= brand.slug
        %td= link_to 'Show', brand
        %td= link_to 'Edit', edit_brand_path(brand)
        %td= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Brand', new_brand_path

app/views/brands/new.html.haml
%h1 New brand

= render 'form'

= link_to 'Back', brands_path

app/views/brands/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @brand.name
%p
  %b Slug:
  = @brand.slug

= link_to 'Edit', edit_brand_path(@brand)
\|
= link_to 'Back', brands_path

app/views/home/index.html.haml
.links
	= link_to "View All Stores", stores_path
	= link_to "View All Brands", brands_path

app/views/home/show.html.erb
New show file
<% if @boolean %>
<%= @some_number %>
<%= @some_number %>
<%= @some_number %>
<% end %>
<%= @some_number %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  -# .field
  -#   = f.label :brand
  -#   = f.text_field :brand
  -# .field
  -#   = f.label :store
  -#   = f.text_field :store
  .field
    = f.label :image
    = f.file_field :image 
  .field
    = f.label :price
    = f.number_field :price 
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
.product_index
  %h1 Listing products

  %table
    %thead
      %tr
        %th Name
        %th Description
        %th Brand
        %th Store
        %th
        %th
        %th

    %tbody
      - @products.each do |product|
        %tr
          %td= product.name
          %td= product.description
          %td= product.brand
          %td= product.store
          %td= link_to 'Show', product
          %td= link_to 'Edit', edit_product_path(product)
          %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Description:
  = @product.description
%p
  %b Brand:
  = @product.brand
%p
  %b Store:
  = @product.store

.image
  = image_tag @product.image(:original)

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path

app/views/stores/_form.html.haml
= form_for @store do |f|
  - if @store.errors.any?
    #error_explanation
      %h2= "#{pluralize(@store.errors.count, "error")} prohibited this store from being saved:"
      %ul
        - @store.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :slug
    = f.text_field :slug
  .actions
    = f.submit 'Save'

app/views/stores/edit.html.haml
%h1 Editing store

= render 'form'

= link_to 'Show', @store
\|
= link_to 'Back', stores_path

app/views/stores/index.html.haml
%h1 Listing stores

%table
  %thead
    %tr
      %th Name
      %th Slug
      %th
      %th
      %th

  %tbody
    - @stores.each do |store|
      %tr
        %td= store.name
        %td= store.slug
        %td= link_to 'Show', store
        %td= link_to 'Edit', edit_store_path(store)
        %td= link_to 'Destroy', store, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Store', new_store_path

app/views/stores/new.html.haml
%h1 New store

= render 'form'

= link_to 'Back', stores_path

app/views/stores/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @store.name
%p
  %b Slug:
  = @store.slug

= link_to 'Edit', edit_store_path(@store)
\|
= link_to 'Back', stores_path